export const kolomMember = [
  {
    key: 'nama',
    label: 'Nama',
  },
  {
    key: 'alamat',
    label: 'Alamat',
  },
  {
    key: 'telepon',
    label: 'Nomor Telepon',
  },
  {
    key: 'tgl_bergabung',
    label: 'Tanggal Bergabung',
  },
  {
    key: 'status',
    label: 'Status Keanggotaan',
  },
  {
    key: 'aksi',
    label: 'Aksi',
  },
];

export const dataMember = [
  {
    key: '1',
    nama: 'Putu Rangga',
    profil: 'https://randomuser.me/api/portraits/men/1.jpg',
    email: 'rangga@gmail.com',
    alamat: 'Jalan Goa Gong 7A',
    telepon: '081246545857',
    tgl_bergabung: '2023-10-28',
    status: 'Aktif',
  },
  {
    key: '2',
    nama: 'Siti Nurul',
    profil: 'https://randomuser.me/api/portraits/men/2.jpg',
    email: 'nurul@gmail.com',
    alamat: 'Jalan Contoh No. 123',
    telepon: '08123456789',
    tgl_bergabung: '2023-10-29',
    status: 'Tidak Aktif',
  },
  {
    key: '3',
    nama: 'Ahmad Fadil',
    profil: 'https://randomuser.me/api/portraits/men/3.jpg',
    email: 'fadil@gmail.com',
    alamat: 'Jalan Percobaan 456',
    telepon: '08125678901',
    tgl_bergabung: '2023-10-30',
    status: 'Aktif',
  },
  {
    key: '4',
    nama: 'Lina Rosita',
    profil: 'https://randomuser.me/api/portraits/men/4.jpg',
    email: 'lina@gmail.com',
    alamat: 'Jalan Uji Coba 789',
    telepon: '08126789012',
    tgl_bergabung: '2023-11-01',
    status: 'Tidak Aktif',
  },
  {
    key: '5',
    nama: 'Adi Prasetyo',
    profil: 'https://randomuser.me/api/portraits/men/5.jpg',
    email: 'adi@gmail.com',
    alamat: 'Jalan Testing 101',
    telepon: '08127890123',
    tgl_bergabung: '2023-11-02',
    status: 'Aktif',
  },
  {
    key: '6',
    nama: 'Maya Indah',
    profil: 'https://randomuser.me/api/portraits/men/6.jpg',
    email: 'maya@gmail.com',
    alamat: 'Jalan Uji Coba 11A',
    telepon: '08128901234',
    tgl_bergabung: '2023-11-03',
    status: 'Tidak Aktif',
  },
  {
    key: '7',
    nama: 'Dian Prima',
    profil: 'https://randomuser.me/api/portraits/men/7.jpg',
    email: 'dian@gmail.com',
    alamat: 'Jalan Contoh 22B',
    telepon: '08129012345',
    tgl_bergabung: '2023-11-04',
    status: 'Aktif',
  },
  {
    key: '8',
    nama: 'Randy Susanto',
    profil: 'https://randomuser.me/api/portraits/men/8.jpg',
    email: 'randy@gmail.com',
    alamat: 'Jalan Percobaan 33C',
    telepon: '08130123456',
    tgl_bergabung: '2023-11-05',
    status: 'Tidak Aktif',
  },
  {
    key: '9',
    nama: 'Nina Putri',
    profil: 'https://randomuser.me/api/portraits/men/9.jpg',
    email: 'nina@gmail.com',
    alamat: 'Jalan Uji 44D',
    telepon: '08131234567',
    tgl_bergabung: '2023-11-06',
    status: 'Aktif',
  },
  {
    key: '10',
    nama: 'Budi Santoso',
    profil: 'https://randomuser.me/api/portraits/men/10.jpg',
    email: 'budi@gmail.com',
    alamat: 'Jalan Testing 55E',
    telepon: '08132345678',
    tgl_bergabung: '2023-11-07',
    status: 'Tidak Aktif',
  },
  {
    key: '11',
    nama: 'Dewi Lestari',
    profil: 'https://randomuser.me/api/portraits/men/1.jpg',
    email: 'dewi@gmail.com',
    alamat: 'Jalan Percobaan 66F',
    telepon: '08133456789',
    tgl_bergabung: '2023-11-08',
    status: 'Aktif',
  },
  {
    key: '12',
    nama: 'Arief Hidayat',
    profil: 'https://randomuser.me/api/portraits/men/2.jpg',
    email: 'arief@gmail.com',
    alamat: 'Jalan Uji Coba 77G',
    telepon: '08134567890',
    tgl_bergabung: '2023-11-09',
    status: 'Tidak Aktif',
  },
  {
    key: '13',
    nama: 'Anita Wijaya',
    profil: 'https://randomuser.me/api/portraits/men/3.jpg',
    email: 'anita@gmail.com',
    alamat: 'Jalan Contoh 88H',
    telepon: '08135678901',
    tgl_bergabung: '2023-11-10',
    status: 'Aktif',
  },
  {
    key: '14',
    nama: 'Rizky Perdana',
    profil: 'https://randomuser.me/api/portraits/men/4.jpg',
    email: 'rizky@gmail.com',
    alamat: 'Jalan Percobaan 99I',
    telepon: '08136789012',
    tgl_bergabung: '2023-11-11',
    status: 'Tidak Aktif',
  },
  {
    key: '15',
    nama: 'Siti Aisyah',
    profil: 'https://randomuser.me/api/portraits/men/5.jpg',
    email: 'aisyah@gmail.com',
    alamat: 'Jalan Testing 101J',
    telepon: '08137890123',
    tgl_bergabung: '2023-11-12',
    status: 'Aktif',
  },
];

export const kolomBuku = [
  {
    key: 'judul_buku',
    label: 'Judul Buku',
  },
  {
    key: 'cover_buku',
    label: 'Cover Buku',
  },
  {
    key: 'penulis_buku',
    label: 'Penulis Buku',
  },
  {
    key: 'bahasa_buku',
    label: 'Bahasa Buku',
  },
  {
    key: 'penerbit_buku',
    label: 'Penerbit Buku',
  },
  {
    key: 'tahun_terbit_buku',
    label: 'Tahun Terbit Buku',
  },
  {
    key: 'jumlah_halaman',
    label: 'Halaman',
  },
  {
    key: 'aksi',
    label: 'Aksi',
  },
];

export const dataBuku = [
  {
    key: '1',
    judul_buku: 'Harry Potter and the Deathly Hallows',
    cover_buku: 'https://covers.openlibrary.org/b/id/14454089-L.jpg',
    penulis_buku: 'J. K. Rowling',
    bahasa_buku: 'Inggris',
    penerbit_buku: 'Arthur A. Levine Books an imprint of Scholastic Inc.',
    tahun_terbit_buku: '2010',
    jumlah_halaman: '759',
  },
  {
    key: '2',
    judul_buku: 'A Game of Thrones',
    cover_buku: 'https://covers.openlibrary.org/b/id/11291394-L.jpg',
    penulis_buku: 'George R. R. Martin',
    bahasa_buku: 'Inggris',
    penerbit_buku: 'Bantam Bookss',
    tahun_terbit_buku: '2002',
    jumlah_halaman: '704',
  },
];

export const kolomPegawai = [
  {
    key: 'nama',
    label: 'Nama',
  },
  {
    key: 'pekerjaan',
    label: 'Pekerjaan',
  },
  {
    key: 'posisi',
    label: 'Posisi',
  },
  {
    key: 'status',
    label: 'Status',
  },
  {
    key: 'aksi',
    label: 'Aksi',
  },
];

export const dataPegawai = [
  {
    key: '1',
    nama: 'Putu Rangga',
    email: 'rangga@gmail.com',
    profil: 'https://randomuser.me/api/portraits/women/1.jpg',
    pekerjaan: 'Pustakawan',
    posisi: 'Kepala Perpustakaan',
    status: 'Aktif',
  },
  {
    key: '2',
    nama: 'Siti Nurul',
    email: 'nurul@gmail.com',
    profil: 'https://randomuser.me/api/portraits/women/2.jpg',
    pekerjaan: 'Asisten Pustakawan',
    posisi: 'Perpustakaan',
    status: 'Tidak Aktif',
  },
  {
    key: '3',
    nama: 'Ahmad Fadil',
    email: 'fadil@gmail.com',
    profil: 'https://randomuser.me/api/portraits/men/3.jpg',
    pekerjaan: 'Pustakawan',
    posisi: 'Kepala Perpustakaan',
    status: 'Aktif',
  },
  {
    key: '4',
    nama: 'Lina Rosita',
    email: 'lina@gmail.com',
    profil: 'https://randomuser.me/api/portraits/women/4.jpg',
    pekerjaan: 'Asisten Pustakawan',
    posisi: 'Perpustakaan',
    status: 'Tidak Aktif',
  },
  {
    key: '5',
    nama: 'Adi Prasetyo',
    email: 'adi@gmail.com',
    profil: 'https://randomuser.me/api/portraits/men/5.jpg',
    pekerjaan: 'Pustakawan',
    posisi: 'Kepala Perpustakaan',
    status: 'Aktif',
  },
  {
    key: '6',
    nama: 'Maya Indah',
    email: 'maya@gmail.com',
    profil: 'https://randomuser.me/api/portraits/women/6.jpg',
    pekerjaan: 'Asisten Pustakawan',
    posisi: 'Perpustakaan',
    status: 'Tidak Aktif',
  },
  {
    key: '7',
    nama: 'Dian Prima',
    email: 'dian@gmail.com',
    profil: 'https://randomuser.me/api/portraits/women/7.jpg',
    pekerjaan: 'Pustakawan',
    posisi: 'Kepala Perpustakaan',
    status: 'Aktif',
  },
  {
    key: '8',
    nama: 'Randy Susanto',
    email: 'randy@gmail.com',
    profil: 'https://randomuser.me/api/portraits/men/8.jpg',
    pekerjaan: 'Asisten Pustakawan',
    posisi: 'Perpustakaan',
    status: 'Tidak Aktif',
  },
  {
    key: '9',
    nama: 'Nina Putri',
    email: 'nina@gmail.com',
    profil: 'https://randomuser.me/api/portraits/women/9.jpg',
    pekerjaan: 'Pustakawan',
    posisi: 'Kepala Perpustakaan',
    status: 'Aktif',
  },
  {
    key: '10',
    nama: 'Budi Santoso',
    email: 'budi@gmail.com',
    profil: 'https://randomuser.me/api/portraits/men/10.jpg',
    pekerjaan: 'Asisten Pustakawan',
    posisi: 'Perpustakaan',
    status: 'Tidak Aktif',
  },
  {
    key: '11',
    nama: 'Dewi Lestari',
    email: 'dewi@gmail.com',
    profil: 'https://randomuser.me/api/portraits/women/1.jpg',
    pekerjaan: 'Pustakawan',
    posisi: 'Kepala Perpustakaan',
    status: 'Aktif',
  },
  {
    key: '12',
    nama: 'Arief Hidayat',
    email: 'arief@gmail.com',
    profil: 'https://randomuser.me/api/portraits/men/2.jpg',
    pekerjaan: 'Asisten Pustakawan',
    posisi: 'Perpustakaan',
    status: 'Tidak Aktif',
  },
  {
    key: '13',
    nama: 'Anita Wijaya',
    email: 'anita@gmail.com',
    profil: 'https://randomuser.me/api/portraits/women/3.jpg',
    pekerjaan: 'Pustakawan',
    posisi: 'Kepala Perpustakaan',
    status: 'Aktif',
  },
  {
    key: '14',
    nama: 'Rizky Perdana',
    email: 'rizky@gmail.com',
    profil: 'https://randomuser.me/api/portraits/men/4.jpg',
    pekerjaan: 'Asisten Pustakawan',
    posisi: 'Perpustakaan',
    status: 'Tidak Aktif',
  },
  {
    key: '15',
    nama: 'Siti Aisyah',
    email: 'aisyah@gmail.com',
    profil: 'https://randomuser.me/api/portraits/women/5.jpg',
    pekerjaan: 'Pustakawan',
    posisi: 'Kepala Perpustakaan',
    status: 'Aktif',
  },
  {
    key: '16',
    nama: 'Andi Prasetya',
    email: 'andi@gmail.com',
    profil: 'https://randomuser.me/api/portraits/men/6.jpg',
    pekerjaan: 'Asisten Pustakawan',
    posisi: 'Perpustakaan',
    status: 'Tidak Aktif',
  },
  {
    key: '17',
    nama: 'Eva Surya',
    email: 'eva@gmail.com',
    profil: 'https://randomuser.me/api/portraits/women/7.jpg',
    pekerjaan: 'Pustakawan',
    posisi: 'Kepala Perpustakaan',
    status: 'Aktif',
  },
  {
    key: '18',
    nama: 'Ricky Santoso',
    email: 'ricky@gmail.com',
    profil: 'https://randomuser.me/api/portraits/men/8.jpg',
    pekerjaan: 'Asisten Pustakawan',
    posisi: 'Perpustakaan',
    status: 'Tidak Aktif',
  },
  {
    key: '19',
    nama: 'Nadia Putri',
    email: 'nadia@gmail.com',
    profil: 'https://randomuser.me/api/portraits/women/9.jpg',
    pekerjaan: 'Pustakawan',
    posisi: 'Kepala Perpustakaan',
    status: 'Aktif',
  },
  {
    key: '20',
    nama: 'Rudi Santoso',
    email: 'rudi@gmail.com',
    profil: 'https://randomuser.me/api/portraits/men/10.jpg',
    pekerjaan: 'Asisten Pustakawan',
    posisi: 'Perpustakaan',
    status: 'Tidak Aktif',
  },
];
